services:
  timestamp:
    container_name: File-Timestamp-App
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: .
      target: /home/File-Timestamp-App
    - type: bind
      source: ~/agent
      target: /agent
      read_only: true
    env_file:
      - .env
    ports:
      - 5173:5173
    stdin_open: true
    tty: true